baseURL = "https://lepovirta.org/"
languageCode = "en-us"
title = "Lepo"
uglyurls = true

[permalinks]
  posts = "posts/:year-:month-:day-:slug"
  tags = "tags/:slug"

[taxonomies]
  tags = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
