language: clojure
notifications:
  slack: lepovirta:v3PaLDZ95F0rcm3WvtDJ84YZ
before_deploy: lein build-site
deploy:
  provider: s3
  access_key_id: AKIAJFPGB7D4DVXCQ7UA
  secret_access_key:
    secure: VgTyiS87QJOoJDi4Ozb+wwm/JzFUGekokk0k7BKCntYo09WlVYxNEQL4hww8wGfwPqZYxuGbdl/NfZiP0VE8HybCJ/uIQ91dfeSPZo2ElOaZX/7CzVc0wH4oObzqEZlmW0c4yCHdjiKXLOUll5JU4B/MTkzJTaWsVCjZIlQHGRJOtlhigYxCgu01ndiW08w+RE1O+oqwF1cnnhagUNDN+JUD3X+t67FfruQJ3R7fuCIqJ8fp7LbMdJMgp25H39Af5yaqNcavPb6e/aXSvLsw965Hs3LIK9hQjpAoNk4dXtiEqbNa4ETqLQwKoUpqApI5CIFMhI9Lml+IY7CNUcFThMcsyDsXxILs98xsggDyOxf/L67KJ9pInql4OgP3wmMwsUcl3b0xtjutKO+AJjcCTr4o3Y5vZ97UoOqgLsJtc9PvE1tczwRdf1s1yRPjELD9et0jwWG4ycOYQHDORSOzpWiyN4yJBogQRcasXojx65pk3Iz6sDcP+Wu604a+bRdbykJCWqci2S9BDIhmCQyJUzGdc0tNYZ2IkUdVik5y8v1VA3ScNWAG6Y/zsYidHX2jtt3Dy0jEhIJgg6hzKzKl2kx8JUxsYTcTDcNiEpNsJNMprQ/apaO3gYlfsIXS/bKgGwg2UYchiHZZEViuixlpQT3SYCZ0NKOkWDSWucPYDpI=
  bucket: aws-website-lepoio-odpfm
  skip_cleanup: true
  local-dir: target/website
  acl: public_read
  detect_encoding: true
  default_text_charset: utf-8
  on:
    repo: Lepovirta/lepo
    branch: master
