language: clojure
after_success:
- CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
before_deploy: sudo pip install awscli
deploy:
  provider: script
  script: "$TRAVIS_BUILD_DIR/scripts/travis_deploy.sh"
  skip_cleanup: true
  on:
    repo: Lepovirta/lepo
    all_branches: true
