language: clojure
notifications:
  slack:
    rooms:
    - lepovirta:v3PaLDZ95F0rcm3WvtDJ84YZ#github
    template:
    - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}
      by %{author} %{result} in %{elapsed_time}: %{message}'
    - Website @ http://staging.lepo.group/%{branch}/
after_success:
- CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
before_deploy: sudo pip install awscli
deploy:
  provider: script
  script: "$TRAVIS_BUILD_DIR/scripts/travis_deploy.sh"
  skip_cleanup: true
  on:
    repo: Lepovirta/lepo
    all_branches: true
