version: 2.1
jobs:
  test:
    docker:
      - image: lepovirta/lepo-build:latest
    steps:
      - checkout
      - run:
          name: test
          command: ./bin/test.sh

  deploy-stg:
    docker:
      - image: lepovirta/lepo-build:latest
    steps:
      - checkout
      - run:
          name: Deploy to staging
          command: STAGING_DIR=$CIRCLE_BRANCH ./bin/generate.sh -t staging -p

  deploy-prod:
    docker:
      - image: lepovirta/lepo-build:latest
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: ./bin/generate.sh -t production -p

workflows:
  version: 2
  all:
    jobs:
      - test
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-stg:
          requires:
            - test
          filters:
            branches:
              ignore: master
