version: 2
jobs:
  build:
    docker:
      - image: lepovirta/lepo-build:latest

    steps:
      - checkout

      - run:
          name: Generate
          command: ./bin/generate.sh --target prod
